#!/bin/sh

# Compile Stuff.
pdflatex -output-directory Jank thesis.tex
cp Library.bib Jank/
cd Jank
#bibtex thesis
biber thesis
makeglossaries thesis
cd ..
pdflatex -output-directory Jank thesis.tex
pdflatex -output-directory Jank thesis.tex

mv Jank/thesis.pdf thesis.pdf
